### ISSUE TITLE
Telos Lands DAO LLC Checklist

### ISSUE THREAD

**Issue by mgravitt** [telosnetwork/landdao-contracts#1]
This ticket describes the process and checklist for establishing the Telos Lands DAO LLC and acquiring property.

The Wyoming DAO LLC statutes, which became effective in July, provide rights of 'personhood' to a smart contract. Namely, these rights include the right to own property. When registering a DAO LLC, the registrant specifies the unique public identifier of the smart contract that will govern that DAO. That LLC, like all LLCs, may acquire property, own bank accounts, and use the court systems if ever needed.  

Here are the steps for this initiative:
- [x] Create a Telos account that will serve as the on-chain identity of the DAO 
- [ ] Create t-starter project to raise funds for the property purchase @jpbeukes
     - Minimum amount to raise should be equivalent to ~$50,000 USD, which would purchase 160 acres if the DAO selected this property (https://horizonlandsales.com/property/160-acres-bordering-over-1-million-acres-of-blm-land-2/)
     - No maximum amount, all contributors become DAO members
     - If minimum threshold of interest is reached, a new business entity named ```Telos Lands DAO LLC``` will be registered in the state of Wyoming
 - [ ] The seller of the property will accept Bitcoin, so the DAO will convert the $50,000 of TLOS tokens to BTC. There are a few options for this: 
      - Swap TLOS tokens for pBTC on-network, and then off-board that pBTC to the seller's wallet (on Coinbase)
      - Ask the seller to create a Telos account, transfer the pBTC to him, and he can off-board the pBTC to his account (or keep it on Telos)
      - Send the TLOS to a cex or dex for conversion to BTC. A cex (and likely multichain dex) will require a trusted agent, so this is not a preferred option. The DAO can require the trusted agent stake funds (as collateral) to the DAO before taking possession of the TLOS, and then return those funds when the property purchase is complete.
      - Another way for a trusted agent to ```stake``` would be a BP to use their reputation. The BP would use their account to attest to a statement that they will serve as the trusted agent, and if they do not perform the duties as defined by the DAO, they would likely lose the trust and votes from the community, thus losing their block rewards.
- [ ] Can a t-starter project integrate with a Telos Decide DAO in order to execute proposals? @jpbeukes
- [ ] DAO votes to make an offer of $x on the property we wish to purchase
- [ ] DAO makes offer on property, which must include a $500 deposit
- [ ] Seller coordinates the creation of a Title Insurance policy via American Title Insurance company. The cost is $200, and this guarantees that there are not creditors that have claims on the property or any known litigation. This policy guarantees that the seller of the property is the actual "free and clear" owner.

**Comment by mgravitt** [comment]
Account is created. https://telos.bloks.io/account/teloslanddao

The smart contract to be deployed to this account is dependent on how Telos Decide integrates with T-Starter.

A likely candidate for this is the ```document-graph``` template, which supports storing and updating of any arbitrary document(s) containing any arbitrary data. This would be used to anchor the various formation documents, images of the properties owned, etc.

**Comment by mgravitt** [comment]
One potentially interesting lens to use when selecting a property relates to tax credits. Specifically, the Sage Grouse tax credit. IIUC, properties that support a healthy Sage Grouse habitat or population can actually EARN by becoming eligible for and selling these tax credits. The specifics of how this is achieved is over my head, but here is the Executive Order on it: https://wgfd.wyo.gov/getattachment/Habitat/Sage-Grouse-Management/Sage-Grouse-Executive-Order/OSLI-Sage-Grouse-Mitigation-Rule.pdf?lang=en-US

**Comment by ghost** [comment]
I have a few questions: 
1. If a token sale is done and say 50 members contribute and buy the land. How will yearly tax be paid?
2. What if some development is to be done on the land, like a Solar farm project? How will decisions be taken by the members?

Can these be Possible Solutions:
1. The Land DAO LLC will be managed by a BP or 'Telos Kitchen' who will be responsible for collecting taxes from the (token) land owners. This can be done yearly through a Smart Contract. If the member doesn't have funds to pay the taxes, or refuses to pay, the Land token can be confiscated through the Smart Contract and will be released upon paying the taxes, with additional fee to the DAO manager.
2. Decide Voter App can be used to create a Group in which decisions regarding the use of Land can be taken. The Vote weight based on the number of Acres (or Tokens) the member has.

Or does Telos Kitchen already have a plan in place for such questions?

**Comment by mgravitt** [comment]
> I have a few questions:
> 
>     1. If a token sale is done and say 50 members contribute and buy the land. How will yearly tax be paid?
> 
>     2. What if some development is to be done on the land, like a Solar farm project? How will decisions be taken by the members?
> 
> 
> Can these be Possible Solutions:
> 
>     1. The Land DAO LLC will be managed by a BP or 'Telos Kitchen' who will be responsible for collecting taxes from the (token) land owners. This can be done yearly through a Smart Contract. If the member doesn't have funds to pay the taxes, or refuses to pay, the Land token can be confiscated through the Smart Contract and will be released upon paying the taxes, with additional fee to the DAO manager.

Yes, that can work. I think the DAO should collect 10 years worth of taxes at the start. It's only $56 / year, so collect $560. 

Somewhat related to this, there is a concept called "Fiscal Host" that we can use. Basically, each DAO can 'hire' a host for this type of minutiae without having to worry about the overhead of creating legacy bank accounts, etc. The idea is described here: https://docs.opencollective.com/help/fiscal-hosts/fiscal-hosts

> 
>     2. Decide Voter App can be used to create a Group in which decisions regarding the use of Land can be taken. The Vote weight based on the number of Acres (or Tokens) the member has.
> 
> 
> Or does Telos Kitchen already have a plan in place for such questions?

I think Decide Voter should be used if possible.

**Comment by ghost** [comment]
Collecting 10 years fee in advance would be a better idea at the moment, and i'm sure relatable tools will be developed in regards to DAO management in the future.

I will go thorough the "Fiscal Host" concept in more detail in the weekend, seems interesting.

Decide Voter would be a great option if all management can be done thorough it, thanks.
